name: fintech
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=2.1.0=py37h03978a9_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py37hcc03f2d_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blosc=1.21.0=h0e60522_0
  - brotli=1.0.9=h0e60522_4
  - brotlipy=0.7.0=py37hcc03f2d_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.5=py37hd8e9650_0
  - chardet=4.0.0=py37h03978a9_1
  - charls=2.2.0=h39d44d4_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.4=py37h65266a2_0
  - cudatoolkit=11.0.221=h74a9793_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py37hcc03f2d_3
  - dask-core=2021.2.0=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h546665d_1
  - giflib=5.2.1=h8d14728_2
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=67.1=h33f27b4_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.1.11=py37hfc4c502_1
  - imageio=2.9.0=py_0
  - importlib-metadata=3.4.0=py37h03978a9_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - intel-openmp=2020.2=254
  - ipykernel=5.4.3=py37heaed05f_0
  - ipython=7.20.0=py37heaed05f_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37h03978a9_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py37h03978a9_0
  - jupyter_server=1.4.0=py37h03978a9_0
  - jupyterlab=3.0.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.2.1=pyhd8ed1ab_0
  - jxrlib=1.1=h8ffe710_2
  - kiwisolver=1.3.1=py37h8c56517_1
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libaec=1.0.4=h39d44d4_1
  - libclang=10.0.1=default_hf44288c_1
  - libdeflate=1.7=h8ffe710_5
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.2.0=hc10be44_0
  - libuv=1.40.0=he774522_0
  - libwebp-base=1.2.0=h8ffe710_0
  - libzopfli=1.0.3=h0e60522_0
  - lime=0.2.0.1=pyh9f0ad1d_0
  - llvmlite=0.35.0=py37habb0c8c_1
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hcc03f2d_3
  - matplotlib=3.3.4=py37h03978a9_0
  - matplotlib-base=3.3.4=py37h3379fd5_0
  - mistune=0.8.4=py37hcc03f2d_1003
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.0.4=py37h343c172_0
  - msys2-conda-epoch=20160418=1
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.2=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h03978a9_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - ninja=1.10.2=py37h6d14046_0
  - notebook=6.2.0=py37h03978a9_0
  - numba=0.52.0=py37h08fd248_0
  - numpy=1.19.1=py37h5510c5b_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h48faf41_0
  - openssl=1.1.1j=h2bbff1b_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.1.3=py37ha925a31_0
  - pandoc=2.11.4=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py37h96663a1_2
  - pip=20.2.4=py37_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h03978a9_7
  - pyqt-impl=5.12.3=py37hf2a7229_7
  - pyqt5-sip=4.19.18=py37hf2a7229_7
  - pyqtchart=5.12=py37hf2a7229_7
  - pyqtwebengine=5.12.1=py37hf2a7229_7
  - pyrsistent=0.17.3=py37hcc03f2d_2
  - pysocks=1.7.1=py37h03978a9_3
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.1=py3.7_cuda110_cudnn8_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37hda49f71_3
  - pywin32=300=py37hcc03f2d_0
  - pywinpty=0.5.7=py37hc8dfbb8_1
  - pyyaml=5.4.1=py37hcc03f2d_0
  - pyzmq=20.0.0=py37h0d95fc2_1
  - qt=5.12.9=hb2cf2c5_0
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-image=0.18.1=py37h08fd248_0
  - scikit-learn=0.23.2=py37h47e9c7a_0
  - scipy=1.5.2=py37h9439919_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py_0
  - setuptools=50.3.0=py37h9490d1a_1
  - shap=0.37.0=py37h08fd248_0
  - six=1.15.0=py_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - snappy=1.1.8=ha925a31_3
  - sniffio=1.2.0=py37h03978a9_1
  - sqlite=3.33.0=h2a8f88b_0
  - statsmodels=0.12.2=py37hda49f71_0
  - terminado=0.9.2=py37h03978a9_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.2.1=pyhd8ed1ab_0
  - tk=8.6.10=h8ffe710_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py37hcc03f2d_1
  - tqdm=4.57.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - win_inet_pton=1.1.0=py37h03978a9_2
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xlrd=1.2.0=py37_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.3=h0e60522_3
  - zfp=0.5.5=h0e60522_4
  - zipp=3.4.0=py_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.8=h4e2f164_1
prefix: C:\Users\Alex\anaconda3\envs\fintech
